name: Build

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  patch_sources:
    name: Patch openvpn sources
    runs-on: ubuntu-22.04
    env:
      OPENVPN_VERSION: ${{ github.ref_name }}
    steps:
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y liblzo2-dev libpam0g-dev liblz4-dev libcap-ng-dev libnl-genl-3-dev linux-libc-dev man2html libcmocka-dev python3-docutils libtool automake autoconf libssl-dev libpkcs11-helper1-dev softhsm2 gnutls-bin

      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout openvpn source code
        uses: actions/checkout@v4
        with:
          repository: OpenVPN/openvpn
          ref: ${{ env.OPENVPN_VERSION }}
          path: openvpn

      - name: Apply patches
        working-directory: openvpn
        run: |
          if [ -d ${{ github.workspace }}/patches/${{ env.OPENVPN_VERSION }}/ ]; then
            for patch_file in $(ls ${{ github.workspace }}/patches/${{ env.OPENVPN_VERSION }}/*.diff); do
          	  patch -p1 -N -i $patch_file
            done
            git diff
          else
            echo Patches for version ${{ env.OPENVPN_VERSION }} not found
            exit 1
          fi

      - name: Create dist
        working-directory: openvpn
        run: |
          autoreconf -fvi
          ./configure
          make dist-gzip

      - name: Upload dist
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: ${{ github.workspace }}/openvpn/openvpn-*.tar.gz
