name: Copy patches

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 */2 * *'

jobs:
  copy_patches:
    name: Copy Tunnelblick patches
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: main

      - name: Checkout Tunnelblick source code
        uses: actions/checkout@v7
        with:
          repository: Tunnelblick/Tunnelblick
          ref: main
          path: Tunnelblick

      - name: Copy patches
        run: |
          counter=0
          for dir in Tunnelblick/third_party/sources/openvpn/*/; do
            dirname=$(basename "$dir")

            # Only accept names exactly like: openvpn-2.6.22

            if [[ ! "$dirname" =~ ^openvpn-([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
              echo "Skip $dirname"
              continue
            fi

            TAG="${BASH_REMATCH[1]}"

            if [ ! -d "patches/v$TAG/" ]; then
              counter=$((counter + 1))
              echo "Copy v$TAG patches"
              mkdir -p "patches/v$TAG/"
              cp "$dir"patches/*openvpn_xorpatch*.diff "patches/v$TAG/"
            fi
          done

          if (( counter == 0 )); then
            echo "No new versions found."
          fi

      - name: Remove Tunnelblick source code
        run: rm -rf Tunnelblick

      - name: Commit patches
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Add new patches from Tunnelblick
          branch: main
